name: alice-dev
services:
  alice:
    image: mcr.microsoft.com/devcontainers/rust:bookworm
    volumes:
      - ..:/workspace:cached  # Mount project root to /workspace
    working_dir: /workspace
    command: sleep infinity

  ollama:
    build:
      context: .
      dockerfile: ollama.dockerfile
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ollama_data:/home/ubuntu/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama_data: