name: alice-dev
services:
  alice:
    image: mcr.microsoft.com/devcontainers/rust:bookworm
    volumes:
      - ..:/workspace:cached  # Mount project root to /workspace
    working_dir: /workspace
    command: sleep infinity
